### ISSUE TITLE
Cnx pack não abre e crashar o console

### ISSUE THREAD

**Issue by Mpmnk9** [AMSNX/CNX-Pack-for-Updater#1]
Nunca tive esse problema, hj ao tentar usar o cnx pack updater tive esse erro
![20230117_233611](https://user-images.githubusercontent.com/122953232/213076613-5a67db53-8ca9-457a-b612-d8e098ffe49a.jpg)

**Comment by AMSNX** [comment]
basta reinstalar o app que volta a funcionar, ou pode tentar também usar a opção no FIX ARCHIVE BIT no hekate
